spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456   # 没密码可不写
      database: 0

  datasource:
    url: jdbc:mysql://localhost:3306/yq
    username: root
    password: 123456

# 支付宝沙箱配置
alipay:
  app-id: 9021000164616717
  gateway-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCoY/4ST0UbKl83YIMqIWghJO2Mz5sTnD4rw0bIrDR3e3oGi8KX1VatPbbyexgbGknXu+AwmFvn6BpuK4J5XtNNDPPR28pNrHCSThvsilrnXva83Zaoa2lNlImeCyr6oKj3CKPn+8HcRuyZ+XzUagdeRfQouDPdX708V1Lx1ob3CCS0FIU3x5Sducob+0C74Ev0Fh+7xQpNHrs+1gRH2wVkgwOeZhKiQXd2MI8ABI6qwvs+P1HRGTjx7tt1QYdXHFsN57pMqE1/vhWOTW8pNuCVV9eRUdIVdtim8mDtdCFyNwsQxMcb98FGXm5SfzdICTgJe9mr4agUgd2Xt67avqrjAgMBAAECggEAEdeGdCoyCE7VB+kR/MTNY7Wl9eWJaOqFK93lAh488OwEYe0tESlppbGEUOz6AOUoLdOaTYvXMRtGsaWqjXGesetNak7/gHtk8huUmduPBjTpr9lKvU2kOrQiYLyOMUAUpxgjRdFHGS/qoeXtdBRH85U16Zqa5DngsyQNhdJVOpdWDquvy+xWYMpEAZt4T/nu2ddD6EEIAwYrieUkTaGzifkzQZXmAYGmjg5GMdeNZqLwqtGb+P4K9YVsUY0DZdSiowkdvC6sHC+hmvufir+cAuvdhX1bIC+09sYnRx8TSLpmWZDoWsyMwhNrf9ncey8uqL7/7TuFLyp7KvFNFPOgAQKBgQDmkeCB3EQiV5j60geqMgiXpjbUON1v0PlmM3sikTI8ms20gv4H19g0giM3TelFulXiVFI7QytihG3VUZFr/z9giEwYzjTGO1ZFXrdIA/l/UXh79OFa5YdU5kGVTWiSonoT4Oc5TTopqNkxKNlVIzJ9Hdmg8xgrQsGsssrpfvyfYwKBgQC69n02ZRgBt1uee4TrDnqMpPJA6VvL4kJJ1acKT81QBpWPAR1wkFKMsmZBRtW1il4U3guCsriauGcAktPn659SIOXszQkMLPfSJ24+gUobkXGgkzC84ayrn9aeTmj2VubhN0Qee2Onl52DPFNwHVSZAYt8seBnMLsXVIn32yRegQKBgFkRv13LHlL57fHu0uEvhNw4bHPdJ8W7P6z4dDftSS/aSV7TP5j+C9p072+83EGAcw8EreOQ1iCvsdI3OWsz5mK/JE5s0jxFzdTsevcJ+gbyDQ4tkiTQCFCGxo0LozsKIwis2AXtzGstfAGemx5lg2qL7ndbkVmc5z50ryg2UxarAoGAZ/pt6LKQh2PSMHHBmniS72VM1Yzy4JEVDLsmCzYWmUsQIlgcZ13ciyMse2FJuY0ahcB35lg/Es07e7Ys4+7GzIY/WVMulPbtXJNRXLHK5UoeR4+Uq3dW8JwUYDZ7aYUrIlX6LHmzEqHfl/0U6mVlhzK0wMSsaLdRVchOcuoNcAECgYEAhW31AXu8bf/ZknXPlGMPD1TyK7qS/sjH/5ZILJjnyRxW1lfSq7u8Yzh8lcxgPSN9bCA4PZv0trgEryNgmUCX1B1IVjmOmlyrhCdSg9lOPxwBgTLOJcS/ck5KjtlMdgj1SsFi4Q+wOAxIknZL9zxa4FXHK6N9HtY3DJaEolPuVAk=
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo+zKVpychg0qUZ2Ui4xTHlxbY3CKCHZXYZ1jiLY66CA7MUFfcPKFP8djYjrTqqG5YFC/cX8moZs6i5XRBbHxTjHC0zpY+j+SQP/QgsnSLyMfd9VmvRFNHUDq3OeN4Jah3xRShjQIHEqF6d9/grBgb28ZKtZQSiNZmBx6MDssxiOqLmk6dHhisP9n16pNsPoo0KmVlx7cp0XY0bXL+KYeA/UvnXhKjaar0WSeqWI9uT69me6O7qkkWJyaRWZrcHGYnbnZoJFJ5wnzOC4xwmqDQPA8A4XB77SrXrCno3gBkGYrwWHVHPmbAKZLwM3D8rVSiTPAkTBGTjj0NeqUE5zsjQIDAQAB
  notify-url: http://b6cd6aa6.natappfree.cc/yq-admin/api/student/pay/notify
  return-url: http://localhost:5174/pay/result