create table if not exists text_to_sql_run (
    id bigint primary key auto_increment comment '主键ID',
    conversation_id varchar(64) not null comment 'LangGraph thread_id / 会话ID',
    parent_run_id bigint null comment '基于历史反馈重新分析时关联原 run',
    source_type varchar(32) not null default 'USER' comment '来源：USER/EVAL',
    original_question text not null comment '用户原始问题',
    final_question text null comment '补充信息合并后的最终问题',
    question_type varchar(32) null comment 'chat/query/update/unclear',
    business_id varchar(64) null comment '业务标识',
    business_name varchar(128) null comment '业务名称',
    route_reason text null comment '路由原因',
    status varchar(32) not null comment 'RUNNING/INTERRUPTED/COMPLETED/FAILED',
    interrupted tinyint(1) not null default 0 comment '是否曾经中断等待补充',
    sql_action varchar(64) null comment 'generate_sql/need_metric/need_schema/need_clarification/out_of_scope/unsupported',
    generated_sql text null comment '模型生成 SQL',
    executed_sql text null comment '最终执行 SQL',
    sql_generation_reason text null comment 'SQL 生成原因',
    execution_error text null comment 'SQL 执行错误',
    used_tables json null comment '使用表',
    used_fields json null comment '使用字段',
    missing_info json null comment '缺失信息',
    query_columns json null comment '查询结果字段',
    query_rows_sample json null comment '查询结果样例，最多保存前20行',
    query_row_count int null comment '查询总行数',
    analysis_summary text null comment '分析摘要',
    analysis_json json null comment '完整分析结果 JSON',
    final_answer text null comment '最终回答',
    state_snapshot_json json null comment '最终 LangGraph state 快照',
    state_snapshot_text longtext null comment 'JSON 过大或兼容性兜底存储',
    feedback_result varchar(32) null comment '最新反馈结果：CORRECT/INCORRECT',
    feedback_error_type varchar(64) null comment '最新错误类型',
    feedback_comment text null comment '最新反馈说明',
    feedback_at datetime null comment '最新反馈时间',
    created_by bigint null comment '提问用户ID',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    unique key uk_text_to_sql_run_conversation_id (conversation_id),
    key idx_text_to_sql_run_source_type (source_type),
    key idx_text_to_sql_run_status (status),
    key idx_text_to_sql_run_feedback_result (feedback_result),
    key idx_text_to_sql_run_business_id (business_id),
    key idx_text_to_sql_run_created_at (created_at)
) comment 'Text-to-SQL 运行记录';

